### ISSUE TITLE
Build issue for kali rolling 2020

### ISSUE THREAD

**Issue by 5l1v3r1** [yakuza8/peniot#1]
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    classifiers=['Programming Language :: Python :: 2.7.9']
  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python2.7/distutils/dist.py", line 259, in __init__
    getattr(self.metadata, "set_" + key)(val)
  File "/usr/lib/python2.7/distutils/dist.py", line 1220, in set_requires
    distutils.versionpredicate.VersionPredicate(v)
  File "/usr/lib/python2.7/distutils/versionpredicate.py", line 113, in __init__
    raise ValueError("expected parenthesized list: %r" % paren)
ValueError: expected parenthesized list: '-mqtt'

Well first of all not all the packages are included in pip repo like python-tkinter etc.. Secondly the files'  places are all wrong like /src/protocols include amqp ble coap etc.. in fact they should be located exactly in /src. Anyway i tried to fix them little bit but didnt work for me.

**Comment by yakuza8** [comment]
I added and fixed build related problems in #2. I made the application be executed. Could you also check and give feedback?

**Comment by yakuza8** [comment]
Even if it builds, program module problem still continues. I will fix it as soon as possible.

**Comment by 5l1v3r1** [comment]
delete every "src." from every python file or mkdir src && cp * /src in the python directory. I fixed it. ( you should do it /usr/local/lib/python2.7/dist-packages/Peniot-1.0-py2.7.egg/ directory).

**Comment by 5l1v3r1** [comment]
I am also turkish btw :)

**Comment by yakuza8** [comment]
It is good to hear :D Btw, new pull request is merged thanks to your attention. Up to now, I was specifying working directory, as a result of that there was no import problem while working in IDE. However, when I run with terminal, it gave import problem. Now, it is solved hopefully. 

You can refer #4 PR. 

Also, let me inform you, I will check #3. By resolution of that, extend utility won't be able to import externally implemented sources.
